/**
 * DancerApplication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RecurFrequency = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

export const RecurFrequency = {
    DAILY: 'DAILY' as RecurFrequency,
    WEEKLY: 'WEEKLY' as RecurFrequency,
    MONTHLY: 'MONTHLY' as RecurFrequency,
    YEARLY: 'YEARLY' as RecurFrequency
};
