/**
 * DancerApplication
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Password } from './password';
import { UserRole } from './userRole';


export interface User { 
    readonly id?: string;
    name?: string;
    password?: Password;
    roles?: Array<UserRole>;
}
